spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pastrycertified
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pastrycertified
    password: scooby060
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5Dialect
